# Generated by Django 6.0.6 on 2026-06-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=5465, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category'),
            preserve_default=False,
        ),
    ]
